stages:
  - train

train-model:
  stage: train
  image: amazon/aws-cli:2.15.0
  rules:
    - if: '$CI_COMMIT_BRANCH == "lesson-10"'
  before_script:
    - aws --version
  script:
    - |
      INPUT_JSON='{"source":"gitlab-ci","commit":"'"$CI_COMMIT_SHORT_SHA"'"}'

      aws stepfunctions start-execution \
        --region "$AWS_DEFAULT_REGION" \
        --state-machine-arn "$STEP_FUNCTION_ARN" \
        --name "train-${CI_COMMIT_SHORT_SHA}-$(date +%s)" \
        --input "$INPUT_JSON"
